services:

#postgres db
  db:
    image: mysql:latest
    container_name: stockmanager_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD="my-secret-pw
      MYSQL_DATABASE=stockmanager
      MYSQL_USER=stockmanager
      MYSQL_PASSWORD=stockmanager
    volumes:
      - ./backend/:/docker-entrypoint-initdb.d:Z
    ports:
      - "5432:5432"

  api:
    image: node:22-slim
    container_name: stockmanager_api
    working_dir: /app
    ports:
      - "3000:3000"
    depends_on:
      - db
    volumes:
      - ./backend:/app:z
      - /app/node_modules
    command: sh -c "npm install && npm start"

# frontend angular (dev)
  frontend:
    image: node:22-slim
    container_name: stockmanager_frontend
    ports:
      - "4200:4200"
    depends_on:
      - api
    working_dir: /app
    volumes:
      - ./frontend:/app:Z
      - /app/node_modules
    command: sh -c "npm install && npm start"
